[package]
name = "php-sys"
version = "0.1.0"
authors = ["haochang hackmasker@gmail.com"]
edition = "2018"
links = "php7"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.51.1"
